config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resource :dashboard
  resources :accounts do
    scope module: :account do
      resources :memberships, only: [:index]
    end
    resources :sources do
      post :import
    end
    resources :photos
  end
end

app/models/source.rb
# == Schema Information
#
# Table name: sources
#
#  id          :bigint           not null, primary key
#  access_key  :string           not null
#  bucket      :string           not null
#  host_base   :string           not null
#  host_bucket :string           not null
#  name        :string           not null
#  secret_key  :string           not null
#  use_http    :boolean          default(TRUE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  account_id  :bigint
#
# Indexes
#
#  index_sources_on_account_id  (account_id)
#
# Foreign Keys
#
#  fk_rails_...  (account_id => accounts.id)
#

class Source < ApplicationRecord
  validates :access_key, presence: true
  validates :bucket, presence: true
  validates :host_base, presence: true
  validates :host_bucket, presence: true
  validates :name, presence: true
  validates :secret_key, presence: true
  validates :use_http, presence: true

  belongs_to :account
  has_many :photos, dependent: :destroy

  def endpoint
    if use_http
      "http://#{host_base}"
    else
      "https://#{host_base}"
    end
  end

  def client
    @client ||= ::Aws::S3::Client.new(
      region: 'us-west-1',
      endpoint: endpoint,
      access_key_id: access_key,
      secret_access_key: secret_key
    )
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  authorize_resource

  before_action :load_account

  def index; end

  def show
    @source = @account.sources.find(params[:id])
    @photos = @source.photos.order(id: 'desc').paginate(page: params[:page], per_page: 60)
  end

  def new
    @source = @account.sources.new
  end

  def edit
    @source = @account.sources.find(params[:id])
  end

  def create
    @source = @account.sources.new(source_params)

    if @source.save
      redirect_to @account
    else
      render :new
    end
  end

  def update
    @source = @account.sources.find(params[:id])

    if @source.update(source_params)
      flash_message(:success)
      redirect_to @account
    else
      render :edit
    end
  end

  def import
    @source = @account.sources.find(params[:source_id])
    SourceImportJob.perform_later(@source)
    flash_message(:success)
    redirect_to @account
  end

  private

  def load_account
    @account = Account.find(params[:account_id])
  end

  def source_params
    params.require(:source).permit(:name, :access_key, :secret_key, :host_base, :host_bucket, :bucket, :use_http)
  end
end

app/views/sources/edit.html.haml
%h1= t '.title'

= simple_form_for @source, url: account_source_path(@account, @source), wrapper: :horizontal_form do |f|
  = f.input :name
  = f.input :access_key
  = f.input :secret_key
  = f.input :host_base
  = f.input :host_bucket
  = f.input :bucket
  = f.input :use_http, wrapper: :horizontal_boolean
  = f.button :submit

app/views/sources/index.html.haml
%h2= t '.title'

- @account.sources.each do |source|
  .row
    .col-md-6
      .card.bg-light.mb-3
        .card-body
          %h5.card-title= source.name
          %p.card-test
            = source.photos.count
            photos (yy other files, zz ignored)
          %ul
            %li
              %b Host Base
              = source.host_base
            %li
              %b Bucket
              s3://#{source.bucket}
          .btn-wrapper
            = link_to t('.show'), account_source_path(@account, source), class: 'btn btn-outline-primary'
            = link_to t('.edit'), edit_account_source_path(@account, source), class: 'btn btn-outline-secondary'
            = button_to t('.import'),
                        account_source_import_path(@account, source),
                        method: :post,
                        class: 'btn btn-outline-secondary'

%p
  = link_to t('.add_source'), new_account_source_path(@account), class: 'btn btn-primary'

app/views/sources/new.html.haml
%h1= t '.title'

= simple_form_for @source, url: account_sources_path(@account), wrapper: :horizontal_form do |f|
  = f.input :name
  = f.input :access_key
  = f.input :secret_key
  = f.input :host_base
  = f.input :host_bucket
  = f.input :bucket
  = f.input :use_http, wrapper: :horizontal_boolean
  = f.button :submit

app/views/sources/show.html.haml
%h1= @source.name

.btn-wrapper
  = link_to t('.edit'), edit_account_source_path(@account, @source), class: 'btn btn-outline-secondary'
  = button_to t('.import'), account_source_import_path(@account, @source), method: :post, class: 'btn btn-outline-secondary'

%h2= t '.photos'

= render partial: 'photo_grid', locals: { photos: @photos, account: @account }