config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resource :dashboard
  resources :accounts do
    scope module: :account do
      resources :memberships, only: [:index]
    end
    resources :sources do
      post :import
    end
    resources :photos
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name == 'notice' ? 'success' : 'danger'}" }
      %button.close{ 'data-dismiss' => 'alert' } ×
      = tag.div(msg, id: "flash_#{name}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Coppermill
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.bg-light.navbar-light.mb-3
      = link_to t('.application_name'), root_path, class: 'navbar-brand'
      .navbar-collapse.collapse
        %ul.navbar-nav
          - if user_signed_in?
            %li.nav-item= link_to t('.dashboard'), dashboard_path, class: 'nav-link'
        %ul.navbar-nav.ml-auto
          - if user_signed_in?
            %li.nav-item= link_to t('.sign_out'), destroy_user_session_path, method: 'delete', class: 'nav-link'
          - else
            %li.nav-item= link_to t('.sign_in'), new_user_session_path, class: 'nav-link'
            %li.nav-item= link_to t('.sign_up'), new_user_registration_path, class: 'nav-link'
    = render 'layouts/messages'
    .container
      = yield