config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resource :dashboard
  resources :accounts do
    scope module: :account do
      resources :memberships, only: [:index]
    end
    resources :sources do
      post :import
    end
    resources :photos
  end
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Account < ApplicationRecord
  validates :name, presence: true

  has_many :account_memberships, dependent: :destroy
  has_many :members, through: :account_memberships, source: :user
  has_many :sources, dependent: :destroy
  has_many :photos, through: :sources
end

app/controllers/account/memberships_controller.rb
class Account::MembershipsController < ApplicationController
  authorize_resource class: false

  before_action :load_account

  def index; end

  private

  def load_account
    @account = Account.find(params[:account_id])
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  authorize_resource

  before_action :load_account

  def show
    @photos = @account.photos.order(id: 'desc').paginate(page: params[:page], per_page: 60)
  end

  def edit; end

  def update
    if @account.update(account_params)
      flash_message(:success)
      redirect_to @account
    else
      flash_message(:failure)
      render :edit
    end
  end

  private

  def load_account
    @account = current_user.accounts.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:name)
  end
end

app/views/accounts/edit.html.haml
%h1= t '.title'

= simple_form_for @account, wrapper: :horizontal_form do |f|
  = f.input :name
  .row
    .col.offset-sm-3
      = f.button :submit

app/views/accounts/show.html.haml
%h1= @account.name

.row.justify-content-between
  .col-auto
    %ul.list-inline
      %li.list-inline-item
        = link_to t('.number_members', count: @account.members.count), account_memberships_path(@account)
      %li.list-inline-item
        = link_to t('.number_sources', count: @account.sources.count), account_sources_path(@account)
  .col-auto
    %p= t '.number_photos', count: @account.photos.count

= render partial: 'photo_grid', locals: { photos: @photos, account: @account }

%h2= t '.scratchspace'

%p
  = link_to t('.edit_account'), edit_account_path(@account), class: 'btn btn-outline-primary'